### ISSUE TITLE
Q12 SVD: Inconsistent expected output for Test Case 2

### ISSUE THREAD

**Issue by hrzhao76** [Open-Deep-ML/DML-OpenProblem#114]
Thank you for preparing these excellent exercises — they’ve been very helpful! 

For **[Problem 12: Singular Value Decomposition (SVD)](https://www.deep-ml.com/problem/Singular%20Value%20Decomposition%20(SVD))**, I noticed an issue with **Test Case 2**, `A = [[1,2],[3,4]]`: the `expected_output` appears to be incorrect, since matrix \( A \) is not symmetric. This means that the matrices \( U \) and \( V \) should not be identical, but they seem to be expected as such in [the test case](https://github.com/Open-Deep-ML/DML-OpenProblem/blob/main/Problems/12_svd_2x2_singular_values/solution.py#L34-L35).

After adding the calculation for \( U \) using the Jacobi method, I encountered an issue related to the sign of the matrices. The new implementation produces the following output for \( U @ np.diag(S) @ V_T \):

```
[[ 1. -2.]
 [ 3. -4.]]
```

This differs from the expected output due to a sign issue. As we know, the sign of the singular vectors in SVD is not uniquely determined, which can cause discrepancies like this. Therefore, I believe we should adopt a **self-consistent choice of signs** for the singular vectors to ensure the output is correct and consistent across different implementations or libraries.

Let me know your thoughts! Thanks.

**Comment by moe18** [comment]
Thank you for letting us know, it should be fixed now
