### ISSUE TITLE
New Problem: Calculate R-squared (Coefficient of Determination)

### ISSUE THREAD

**Issue by rittik9** [Open-Deep-ML/DML-OpenProblem#122]
## Problem Description
This problem will test the implementation of the R-squared (R²) coefficient, a fundamental statistical measure used to evaluate the goodness of fit in regression models.

## Importance
The R-squared coefficient (coefficient of determination) measures how well a regression model fits the observed data. It represents the proportion of variance in the dependent variable that is predictable from the independent variable(s).

## Mathematical Definition
R² is calculated as:
```R² = 1 - (SSR/SST)```

Where,
- SSR  = Sum of Squared Residuals
- SST  = Total Sum of Squares

## Reference:
https://www.ncl.ac.uk/webtemplate/ask-assets/external/maths-resources/statistics/regression-and-correlation/coefficient-of-determination-r-squared.html

**Comment by moe18** [comment]
all yours

**Comment by rittik9** [comment]
pls let me know the problem no.

**Comment by moe18** [comment]
You could use 70, I am going to refactor at some point and fix up the ids but for now just use 70

**Comment by rittik9** [comment]
[](https://github.com/Open-Deep-ML/DML-OpenProblem/pull/125)
here is the pr for the issue
