### ISSUE TITLE
New Problem: Image Brightness Calculator

### ISSUE THREAD

**Issue by NiharP31** [Open-Deep-ML/DML-OpenProblem#123]
I would like to contribute a new problem focused on basic computer vision concepts.

**Problem Overview:**
- Title: Image Brightness Calculator
- Difficulty: Easy
- Category: Computer Vision
- Concepts Covered: Image processing, array manipulation, basic statistics

**Learning Objectives:**
- Understanding image representation in programming
- Working with 2D arrays
- Basic image statistics calculation
- Input validation for image data

**Brief Problem Statement:**
Create a function that calculates the average brightness of a grayscale image represented as a 2D list of integers (0-255).

**Example Implementation Available:** Yes
**Test Cases:** Ready
**Documentation:** Will include detailed explanations and comments

I can start working on this once assigned a problem number.

**Comment by moe18** [comment]
Sounds great, all yours

**Comment by NiharP31** [comment]
Thank you!!
What number should I assign to this problem?

**Comment by NiharP31** [comment]
I haven't got the question number for this.

**Comment by NiharP31** [comment]
I have pushed  the commit

**Comment by NiharP31** [comment]
I have more incoming!!!
