### ISSUE TITLE
New Problem : Root Means Square Error (RMSE)

### ISSUE THREAD

**Issue by saitiger** [Open-Deep-ML/DML-OpenProblem#124]
Implementation of RMSE, along with the theory for when RMSE is appropriate compared to Mean Absolute Error for the learn section.

**Comment by moe18** [comment]
All yours

**Comment by saitiger** [comment]
Let me know the problem number.

**Comment by moe18** [comment]
You could make it 71

**Comment by saitiger** [comment]
Is there any limit on the number of test cases ? 
I want to add some test cases for edge cases, for example, when the length of the two arrays is not the same.

**Comment by moe18** [comment]
There is no hard limit I'd say try and keep it less then 5 but you could add more if needed
