### ISSUE TITLE
New Problem: Jaccard Index

### ISSUE THREAD

**Issue by rittik9** [Open-Deep-ML/DML-OpenProblem#127]
# Jaccard Index

The **Jaccard Index**, also known as the **Jaccard similarity coefficient**, is a statistic used to measure the similarity between two sets. It is defined as the size of the intersection divided by the size of the union of the sample sets.

## Formula

The formula for calculating the Jaccard Index is:

$$
J(A, B) = \frac{|A \cap B|}{|A \cup B|}
$$

## Application in Image Segmentation

In the context of image segmentation, the Jaccard Index quantifies how well the predicted segmentation matches the ground truth. It is particularly useful for evaluating performance in tasks such as object detection and semantic segmentation.

### Characteristics
- **Range**: The Jaccard Index ranges from 0 to 1.
  - A value of **0** indicates no overlap between the sets.
  - A value of **1** indicates perfect overlap.
  
- **Sensitivity**: The Jaccard Index is sensitive to small changes in segmentation, making it a robust metric for evaluating model performance.

## Example Calculation

Given two sets:
- Set A: {1, 2, 3}
- Set B: {2, 3, 4}

The Jaccard Index can be calculated as follows:

1. **Intersection**: = |{2, 3}|  = 2
2. **Union**:  = |{1, 2, 3, 4}| = 4

Thus, 

$$
J(A, B) = \frac{2}{4} = 0.5
$$

This indicates a moderate level of similarity between the two sets.

**Comment by moe18** [comment]
All yours, prob number 72
