### ISSUE TITLE
New Problem: Dice Score

### ISSUE THREAD

**Issue by rittik9** [Open-Deep-ML/DML-OpenProblem#128]
# Dice Coefficient

The **Dice Coefficient**, also known as the **Dice Similarity Coefficient**, is a statistic used to measure the similarity between two sets. It is particularly useful in the context of image segmentation and is defined as twice the size of the intersection divided by the sum of the sizes of both sets.

## Formula

The formula for calculating the Dice Coefficient is:

$$
D(A, B) = \frac{2 |A \cap B|}{|A| + |B|}
$$

## Application in Image Segmentation

In the context of image segmentation, the Dice Coefficient quantifies how well the predicted segmentation matches the ground truth. It is especially sensitive to small changes in segmentation, making it a valuable metric for evaluating model performance.

### Characteristics
- **Range**: The Dice Coefficient ranges from 0 to 1.
  - A value of **0** indicates no overlap between the sets.
  - A value of **1** indicates perfect overlap.
  
- **Sensitivity**: The Dice Coefficient is more sensitive to small changes than other metrics, which makes it particularly useful in medical imaging applications.

## Example Calculation

Given two sets:
- Set A: {1, 2, 3}
- Set B: {2, 3, 4}

The Dice Coefficient can be calculated as follows:

1. **Intersection**: |{2, 3}| = 2 

2. **Size of Set A**: |A| = |{1, 2, 3}| = 3 

3. **Size of Set B**: |B| = |{2, 3, 4}| = 3

Thus,

$$
D(A, B) = \frac{2 \cdot 2}{3 + 3} = \frac{4}{6} = \frac{2}{3} \approx 0.67
$$

This indicates a moderate level of similarity between the two sets.

**Comment by moe18** [comment]
All yours, problem number 73
