### ISSUE TITLE
Contribute LLM interview questions

### ISSUE THREAD

**Issue by hydrogeohc** [Open-Deep-ML/DML-OpenProblem#16]
Add some recent LLM interview questions here

**Comment by moe18** [comment]
Hi @hydrogeohc would you be able to add some more details about the problem you would like to add (for example will this be a problem about how to create a transformer?

**Comment by hydrogeohc** [comment]
yeah, 1) explain the transformer architecture 2)  What are the different categories of the PEFT method for LLM?

**Comment by moe18** [comment]
hey @hydrogeohc, just wanted to check on your progress for this

**Comment by hydrogeohc** [comment]
Hey @moe18 I will try to get it done this weekend. Thanks!

**Comment by moe18** [comment]
hey @hydrogeohc, just wanted to check on your progress for this
