### ISSUE TITLE
New problem : Positional Encoding for Tranformers input

### ISSUE THREAD

**Issue by dsaha21** [Open-Deep-ML/DML-OpenProblem#165]
I want to add a easy to medium question on NLP category related to Transformers positional encoding upon the input embeddings. The question will be done using only `tensorflow as tf, tf.cast(), tf.concat(), tf.math.sin()  and tf.math.cos()`.
If possible, I might open a PR 

If that goes succesfull, we might add more transformer blocks :
1. Self attention
2. Multihead attention
3. Encoder 
4. Decoder 
5. Full Transformer - > N x Encoder and Decoder blocks (hard level question)(also if all segments are performed we can think of adding this)

Thank you

**Comment by moe18** [comment]
Currently, our platform supports only NumPy. While we may expand to include other libraries in the future, for now, all our implementations are exclusively built with NumPy.

**Comment by dsaha21** [comment]
Okay sure :+1: 

Then I am closing the issue for now. Will try to add other problems with numpy. Thanks a lot @moe18

**Comment by dsaha21** [comment]
Problem added, closing the issue
