### ISSUE TITLE
New Problem: Probability distributions

### ISSUE THREAD

**Issue by BhardwajArjit** [Open-Deep-ML/DML-OpenProblem#166]
I think a problem on probability distributions (e.g., binomial, Poisson, normal) would be a good one to add.

**Comment by moe18** [comment]
I think so as well, would you like to work on this problem or are you just recommending possible new problems?

**Comment by BhardwajArjit** [comment]
Definitely, I would like to work on this problem. I've already opened the pull request (#153) for the descriptive stats ques (#136). Please review that and assign this to me. Thanks!
