### ISSUE TITLE
19_PCA output format bug

### ISSUE THREAD

**Issue by jon-rosen** [Open-Deep-ML/DML-OpenProblem#204]
question 19_PCA does the following operation as final step in solution:

return np.round(principal_components, 4).tolist()

However this is wrong, in one of the test cases it results in a 2-element eigenvector being the accepted solution for a 3x3 covariance matrix which is impossible. 

The problem is that np.ndarray.tolist() is carried out on the wrong dimension. The correct solution should include transpose as follows:

return np.round(principal_components.T, 4).tolist()

**Comment by moe18** [comment]
By using `return np.round(principal_components.T, 4).tolist()`, you end up with an incorrect shape. For the given input, the result becomes:

```python
[[0.6855, 0.6202, -0.3814],
 [0.0776, 0.4586, 0.8853]]
```
This is a 2x3 matrix, whereas the function should return a 3x2 matrix. Here’s why:

Before transposing, principal_components has the shape (n_features, k). With 3 features and k=2, it is (3, 2).
After transposing, principal_components.T becomes (2, 3), which is not the desired shape.

let me know if this makes sense or if I missed something

**Comment by jon-rosen** [comment]
Well this is a list of principle components, so whether it is 3x2 or 2x3 isn't really important. What is important is that the inner list after converting np.array.tolist() has three elements. The answer currently expects a list of 2-element lists, whereas it should expect a list of 3-element lists. 2x3 and 3x2 only matters for arrays, but this question expects a list of lists.

**Comment by moe18** [comment]
So if I changed the required output to be a numpy array would that fix the issue?

**Comment by jon-rosen** [comment]
Yeah that would be an improvement here. I was quite confused when my answer didn't pass the test and that it required a list of 2-element vectors until I backed-out that it was due to this np.array.tolist behavior. If it just expects an array then at most I am off by a transpose, so much easier to understand the correct output format.

**Comment by moe18** [comment]
fixed
https://www.deep-ml.com/problems/19
