### ISSUE TITLE
Can't find "Implementing Basic Autograd Operations" in the repo

### ISSUE THREAD

**Issue by ragprab** [Open-Deep-ML/DML-OpenProblem#205]
I was working on "Implementing Basic Autograd Operations" as problem 26 on deep-ml.com. Here is the [deep-ml link](https://www.deep-ml.com/problem/Implementing%20Basic%20Autograd%20Operations) to this problem.

I found a couple of issues.

Issue 1: Example output seems to be wrong.

a = Value(2)
b = Value(-3)
c = Value(10)
d = a + b * c
e = d.relu()
e.backward()
print(a, b, c, d, e)
Output: Value(data=2, grad=0) Value(data=-3, grad=10) Value(data=10, grad=-3) Value(data=-28, grad=1) Value(data=0, grad=1)

I think the gradients for all nodes except e should be 0, since d is negative, so gradients of d and all of its children should be 0.

Issue 2:

I couldn't find this problem in https://github.com/Open-Deep-ML/DML-OpenProblem/tree/main/Problems. The directory structure seems to skip from Problem 25 to 28; I couldn't find Problems 26 and 27 in the repo (despite them existing on the website). I don't mind submitting a PR to fix the example output once I know how to find Problem 26.

**Comment by moe18** [comment]
yes it seems like the example is wrong, will fix shortly

also, I will add the problem to the repo because it is missing

thank you for letting us know!
