### ISSUE TITLE
Batch Iterator Awkward Interpretation

### ISSUE THREAD

**Issue by mindful-math** [Open-Deep-ML/DML-OpenProblem#206]
In [this problem](https://www.deep-ml.com/problem/Batch%20Iterator%20for%20Dataset), it asks for a batch iterator but your test cases expect an *iterable*. Either a) swap iterator with iterable or b) swap the test cases to expect an iterator.

**Comment by moe18** [comment]
I updated the problem description thank you for letting us know

https://www.deep-ml.com/problems/30
