### ISSUE TITLE
fix to Jacobi algorithm description

### ISSUE THREAD

**Issue by diegoasua** [Open-Deep-ML/DML-OpenProblem#215]
Problem states

>Write a Python function that uses the Jacobi method to solve a system of linear equations given by Ax = b. The function should iterate 10 times, rounding each intermediate solution to four decimal places, and return the approximate solution x.

But the problem statement provides `n` which is the number of iterations. fix:

>Write a Python function that uses the Jacobi method to solve a system of linear equations given by Ax = b. The function should iterate n times, rounding each intermediate solution to four decimal places, and return the approximate solution x.

**Comment by moe18** [comment]
Fixed, thank you for letting us know, it should be on the website in 30 min
