### ISSUE TITLE
incorrect reference implementation of 2x2 SVD for problem 12

### ISSUE THREAD

**Issue by diegoasua** [Open-Deep-ML/DML-OpenProblem#216]
Given SVD by $U \Sigma V$ the reference implementation makes $U = V^{T}$ which is incorrect. In the [reference implementation](https://github.com/Open-Deep-ML/DML-OpenProblem/blob/f8f2b22ac667a938a74fb77ae425730d2f323b41/Problems/12_svd_2x2_singular_values/solution.py#L1C1-L15C35) this matrix is referred to as $j$ 

I suggest this example instead:

```python
import numpy as np 


def svd_2x2_singular_values(A: np.ndarray) -> tuple:
   # stick to lowercase
   a = A

   a_t = np.transpose(a)
   a_2 = a_t @ a

   v = np.eye(2)

   for _ in range(1):
       # Compute rotation angle for a 2x2 matrix
       if a_2[0,0] == a_2[1,1]:
           theta = np.pi/4
       else:
           theta = 0.5 * np.arctan2(2 * a_2[0,1], a_2[0,0] - a_2[1,1])
       
       # Create rotation matrix
       r = np.array(
           [
               [np.cos(theta), -np.sin(theta)],
               [np.sin(theta), np.cos(theta)]
               ]
           )
       
       # apply rotation
       d = np.transpose(r) @ a_2 @ r

       # update a_2
       a_2 = d

       # accumulate v
       v = v @ r

   # sigma is the diagonal elements squared
   s = np.sqrt([d[0,0], d[1,1]])
   s_inv = np.array([[1/s[0], 0], [0, 1/s[1]]])
   
   u = a @ v @ s_inv
   
   return (u, s, v.T)
```

I checked the output of `numpy.linalg.svd` and this code much closer to the numpy implementation than the provided one.

```bash
>>> a = np.array([[1, 2], [3, 4]])
>>> np.linalg.svd(a)
SVDResult(U=array([[-0.40455358, -0.9145143 ],
       [-0.9145143 ,  0.40455358]]), S=array([5.4649857 , 0.36596619]), Vh=array([[-0.57604844, -0.81741556],
       [ 0.81741556, -0.57604844]]))
```
For $U$:

the wrong implementation yields `(array([[ 0.57604844, -0.81741556], [ 0.81741556, 0.57604844]])`
the proposed one here yields `(array([[ 0.40455358, 0.9145143 ], [ 0.9145143 , -0.40455358]])`
`numpy.linalg.svd` yields `array([[-0.40455358, -0.9145143 ], [-0.9145143 ,  0.40455358]])`

Unsure about the sign discrepancies wrt numpy reference, but the floats are the same.

**Comment by Open-Deep-ML** [comment]
Thank you for letting us know we have fixed the problem on the site and will change it here shortly
https://www.deep-ml.com/problems/12
