### ISSUE TITLE
Updating base problem set

### ISSUE THREAD

**Issue by moe18** [Open-Deep-ML/DML-OpenProblem#22]
Need to Update the main Problem set to include what is already on deep-ml (problems 20-40)

**Comment by doshi-kevin** [comment]
Hi, I am an aspiring developer and a machine learning enthusiast, could you please help to contribute to open source and also a procedure like how can I contribute to this project.

**Comment by moe18** [comment]
Sure thing, there are a lot of ways you could help out with this project, you could edit a solution, create a new problem, edit a learn section or create a learn section. all contributions are much apricated. here is a good link about how to contribute to open source in general https://www.freecodecamp.org/news/how-to-contribute-to-open-source-projects-beginners-guide/, and below is the steps to contribute to this repo.

## Create a new Problem
1. Create an issue describing the problem you would like to work on, give it the label New Problem and comment that you would like to work on it
2. Fork the repository.
3. Create a new branch for your feature or bugfix.
4. Make your changes and commit them with clear and concise messages.
5. Push your changes to your fork.
6. Submit a pull request with a detailed description of your changes.
