### ISSUE TITLE
Some Problem Descriptions Not Clear

### ISSUE THREAD

**Issue by peppermin-t** [Open-Deep-ML/DML-OpenProblem#42]
**One-Hot Encoding of Nominal Values**: It's not very clear that whether the nominal values start from 0 & the users should consider only encoding consistent values or inconsistent values which they can encode it in a more compact way, such as [0, 10, 2] corresponds to only 3 digit one-hot encoding instead of 11 digits.

**Solve Linear Equations using Jacobi Method**: It's not clear which `x` the users should start from (should be np.zeros by default) & the iteration count is actually the given `n` instead of a set `10`.

**Comment by peppermin-t** [comment]
Also for Q33 [Generate Random Subsets of a Dataset](https://www.deep-ml.com/problem/Generate%20Random%20Subsets%20of%20a%20Dataset), I think there's no need for the solution to shuffle the dataset before np.choice, rendering the expected output also invalid.

I can offer my solution and correct the expected output for test instances, but I cannot find Q33 in the repo an do a PR.

**Comment by peppermin-t** [comment]
For Q32 [Generate Polynomial Features](https://www.deep-ml.com/problem/Generate%20Polynomial%20Features), I can also offer a conciser solution. Could you open the codes for these missing questions so that PR can be made?

**Comment by Open-Deep-ML** [comment]
> **One-Hot Encoding of Nominal Values**: It's not very clear that whether the nominal values start from 0 & the users should consider only encoding consistent values or inconsistent values which they can encode it in a more compact way, such as [0, 10, 2] corresponds to only 3 digit one-hot encoding instead of 11 digits.
> 
> **Solve Linear Equations using Jacobi Method**: It's not clear which `x` the users should start from (should be np.zeros by default) & the iteration count is actually the given `n` instead of a set `10`.

will look into this, thank you for the comment 👍
