### ISSUE TITLE
Issue on question [Solve Linear Equations using Jacobi Method (medium)]

### ISSUE THREAD

**Issue by Kim-Eungseo** [Open-Deep-ML/DML-OpenProblem#60]
I suggest to update question condition to "n times" and set initial value to np.zeros(len(b))

**Comment by moe18** [comment]
will look into this this week or next, thanks for letting me know

**Comment by moe18** [comment]
made the suggested changes
https://www.deep-ml.com/problem/Solve%20Linear%20Equations%20using%20Jacobi%20Method
