### ISSUE TITLE
25 Single neuron with backporop example issue

### ISSUE THREAD

**Issue by andrew-kovalenk0** [Open-Deep-ML/DML-OpenProblem#68]
In the example expected output is: updated_weights = [0.0808, -0.1916], updated_bias = -0.0214, mse_values = [0.2386, 0.2348].
If run solution code with inputs from the example output will be ([0.1036, -0.1425], -0.0167, [0.3033, 0.2942]).

**Comment by moe18** [comment]
made the suggested changes
https://www.deep-ml.com/problem/Single%20Neuron%20with%20Backpropagation
