### ISSUE TITLE
New Problem: 2D Translation Matrix Implementation

### ISSUE THREAD

**Issue by Mohamad-Abdulkadir** [Open-Deep-ML/DML-OpenProblem#69]
I want to contribute a new problem focused on implementing a 2D translation matrix function given a set of points and the vertical and horizontal translation amounts. 
The problem will cover:
- Creating a function that applies a 2D translation to a set of points representing an object and implementing it using NumPy 
- Handling the conversion between regular and homogeneous coordinates

This will be a "Medium" difficulty problem in the linear algebra category.

**Comment by moe18** [comment]
sounds good, make it problem 56
