### ISSUE TITLE
New Problem: Gaussian Elimination with Partial Pivoting

### ISSUE THREAD

**Issue by paddywardle** [Open-Deep-ML/DML-OpenProblem#71]
I want to add a new problem on applying gaussian elimination with partial pivoting to solve a linear system of equations.

The problem will cover:

- Elimination
- Backward subsititution
- Partial Pivoting
- Implementation of gaussian elimination in NumPy

This will be a "Medium" difficulty problem in the linear algebra category.

**Comment by moe18** [comment]
all yours
