### ISSUE TITLE
New Problem: Gauss-Seidel Method

### ISSUE THREAD

**Issue by paddywardle** [Open-Deep-ML/DML-OpenProblem#74]
Thought this would be good to add to contrast the Jacobi solver problem.

The problem will cover:
- The implementation of the Gauss-Seidel solver.

This will be a "Medium" difficulty problem in the linear algebra category.

**Comment by moe18** [comment]
would you like to work on this, or were you just suggesting the problem?

**Comment by paddywardle** [comment]
Yeah I’d like to work on this 😊
