### ISSUE TITLE
Question on Problem#41

### ISSUE THREAD

**Issue by CharlotteE67** [Open-Deep-ML/DML-OpenProblem#85]
I wonder whether the example shown in the [problem#41](https://www.deep-ml.com/problem/Simple%20Convolutional%202D%20Layer) is incorrect.

> Example:
> import numpy as np
> 
> input_matrix = np.array([
>     [1, 2, 3, 4],
>     [5, 6, 7, 8],
>     [9, 10, 11, 12],
>     [13, 14, 15, 16]
> ])
> 
> kernel = np.array([
>     [1, 0],
>     [-1, 1]
> ])
> 
> padding = 1
> stride = 2
> 
> output = simple_conv2d(input_matrix, kernel, padding, stride)
> print(output)
> Expected Output:
> [[  3.   9.]
>  [ 11.  17.]]

The expected output should be:
> [[ 1.  1. -4.]
>  [ 9.  7. -4.]
>  [ 0. 14. 16.]]

**Comment by andrew-kovalenk0** [comment]
Yes, it's incorrect, you're right. Also there is mismatching in the Test Case 2, Expected values are differ.
![изображение](https://github.com/user-attachments/assets/8d894263-2432-41a4-89a9-4d85973d0b77)

**Comment by moe18** [comment]
that is strange I will check that out, thanks for letting us know

**Comment by moe18** [comment]
Fixed it
