### ISSUE TITLE
Sparse Matrices

### ISSUE THREAD

**Issue by paddywardle** [Open-Deep-ML/DML-OpenProblem#89]
This could be a few problems, so looking at compressed row, compressed column, simple index sparse matrices.

**Comment by moe18** [comment]
would you be able to give a little more information about this one?

**Comment by paddywardle** [comment]
So could start with just a problem just converting a dense array to a compressed row or column sparse matrix format. Then in the future we could add problem for linear algebra operations on sparse matrices, but will just start with the format

**Comment by moe18** [comment]
That sounds like a good problem. I feel like it will help people get more comfortable with formatting matrices
